//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeekEntities : DbContext
    {
        public GeekEntities()
            : base("name=GeekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<System_LogEvents> System_LogEvents { get; set; }
        public DbSet<System_Services> System_Services { get; set; }
        public DbSet<System_Logs> System_Logs { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
