//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Logs
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int EventId { get; set; }
        public string Message { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual System_LogEvents System_LogEvents { get; set; }
        public virtual System_Services System_Services { get; set; }
    }
}
